import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Main.module.css'
import React, { Component } from 'react'
import { getThreeWords } from '../public/three_words_generator/three_words_generator'

export interface MainState {
  count: number;
}

export interface MainProps {}

export default class Main extends Component<MainProps, MainState> {

  constructor(props: MainProps) {
    super(props)
    this.state = {
      count: 0
    }
  }

  componentDidMount() {}

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            DEV-CHAT
          </h1>
          <div>Count={this.state.count}</div>
          <button onClick={() => {
            this.setState({ count: this.state.count + 1 });
          }}> plus 1 </button>
        </main>
      </div>
    )
  }
}