import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Main.module.css'
import React, { Component } from 'react'
import { IChatMessage, IUser } from '../public/interfaces'

export interface MainState {
  count: number;
}

export interface MainProps {}

export default class Main extends Component<MainProps, MainState> {

  constructor(props: MainProps) {
    super(props)
    this.state = {
      count: 0
    }
  }

  async componentDidMount() {
    let result = await this.verifyUser("Broadcast", "1234");
    console.log(result);

    let messages = await this.getChatMessages("HelloWorldGuys");
    console.log(messages);
  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            DEV-CHAT
          </h1>
          <div>Count={this.state.count}</div>
          <button onClick={() => {
            this.setState({ count: this.state.count + 1 });
          }}> plus 1 </button>
        </main>
      </div>
    )
  }

  /**
   * This is a function that removes a user from the database
   * @param {string} username the username of the user to be removed
   * @param {string} password the password of the user to be removed
   * @returns {Promise<boolean>} true if the user was removed, false if the user was not found or the password was wrong
   **/
  public deleteUser = async (username: string, password:string): Promise<boolean> => {
    let response = await fetch('./api/delete_user', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        username: username,
        password: password
      })
    });
    let data = await response.json();
    return data.wasSuccessfull;
  }

  /**
   * This is a function that removes a user from the database
   * @param {string} username the username of the user to be removed
   * @param {string} password the password of the user to be removed
   * @returns {Promise<boolean>} true if the user was removed, false if the user was not found or the password was wrong
   **/
  public verifyUser = async (username: string, password:string): Promise<boolean> => {
    let response = await fetch('./api/verify_user', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        username: username,
        password: password
      })
    });
    let data = await response.json();
    return data.wasSuccessfull;
  }

  public getChatMessages = async (threeword: string): Promise<IChatMessage[]> => {
    let response = await fetch('./api/get_chat_messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        threeword: threeword
      })
    });
    let data = await response.json();
    return data.chatMessages ? data.chatMessages : [];
  }
}