import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Login.module.css'
import React, { Component } from 'react'

export interface LoginState {
}

export interface LoginProps {}
/**
 * @class Login Componet Class
 * @component
 */
class Login extends Component<LoginProps, LoginState> {
  username = '';
  password = '';
  constructor(props: LoginProps) {
    super(props)
    this.state = {
    }
    
  }
  /**
   * is always called, if component did mount
   */
  componentDidMount() {}
  /**
   * Generates the JSX Output for the Client
   * @returns JSX Output
   */
  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.Login}>
          <h1 className={styles.title}>
            Log-In
          </h1>
          <input type="text" placeholder="Username..." onChange={(event) => {this.username = event.target.value}}/>
          <input type="password" placeholder="Password..." onChange={(event) => {this.password = event.target.value}}/>
          <button onClick={() => {
              this.clickedLogin();
          }}> Login </button>
          <div>Or <a href={"/register"}>create Account</a> instead</div>
        </main>
      </div>
    )
  }
  /**
   * Button Click Event for the Login Button
   */
  clickedLogin() {
    alert(`username: ${this.username} password: ${this.password}`);
  }
}

export default Login