import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Register.module.css'
import React, { Component } from 'react'

export interface RegisterState {
}

export interface RegisterProps {}
/**
 * @class Class of the register Component
 * @component
 */
class Register extends Component<RegisterProps, RegisterState> {
  username = '';
  password = '';
  constructor(props: RegisterProps) {
    super(props)
    this.state = {
    }
    
  }
  /**
   * is always called, if component did mount
   */
  componentDidMount() {}
  /**
   * Generates the JSX Output for the Client
   * @returns JSX Output
   */
  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.Register}>
          <h1 className={styles.title}>
            Log-In
          </h1>
          <input type="text" placeholder="Username..." onChange={(event) => {this.username = event.target.value}}/>
          <input type="password" placeholder="Password..." onChange={(event) => {this.password = event.target.value}}/>
          <button onClick={() => {
              this.clickedRegister();
          }}> Register </button>
          <div>Or <a href={"/login"}>login</a> instead</div>
        </main>
      </div>
    )
  }
  /**
   * Button Click Event for the Register Button
   */
  clickedRegister() {
    alert(`username: ${this.username} password: ${this.password}`);
  }
}
export default Register